---
subtitle: "Week 2: Linux Syscalls 101 and processes"
# bibliography: references/week1.bib
format: revealjs
---

# Goals for today

-   Any questions from the previous session?
-   Learn how the kernel reacts to external input.
-   Understand how we interact with the kernel and ProcFS.
-   Present and explain Prac-2.1

# Recap

# Interactions with the kernel
Explain what an interrupt is (briefly)
- https://linux-kernel-labs.github.io/refs/heads/master/lectures/interrupts.html


# How we (as users) interact with the kernel
Syscalls (interrupts)
- https://filippo.io/linux-syscall-table/
- https://linux-kernel-labs.github.io/refs/heads/master/lectures/syscalls.html

# Processes, threads, and kthreads

- https://linux-kernel-labs.github.io/refs/heads/master/lectures/processes.html#lecture-objectives
- https://dengking.github.io/Linux-OS/Kernel/Book-Understanding-the-Linux-Kernel/Chapter-3-Processes/3.4.2-Kernel-Threads/
- https://www.man7.org/linux/man-pages/man2/clone.2.html

# ProcFS
- https://docs.kernel.org/filesystems/proc.html
- https://github.com/htop-dev/htop/issues/99
- https://peteris.rocks/blog/htop/

# Quizz

# References

## Really Recommended References: {.smaller}

-   Example: <https://example.com>

-   Example2: <https://example2.com>


## Other recommended references:

-   https://0xax.gitbooks.io/linux-insides/content/SysCall/linux-syscall-1.html

## Additional Exercices {.smaller}

If you really want to understand a little bit more what happens under the hood, you can do the following exercices. Be aware that you should read the "Really Recommended References" first, and then try to do this exercices.

-   Create your own syscall: https://amsa-2425.github.io/Laboratoris/Kernel/add-syscalls.html?highlight=syscall#afegint-una-crida-a-sistema and https://www.youtube.com/watch?v=Kn6D7sH7Fts .

## Activity 2.1 {.smaller}

Ready to have some fun? Check out the [second AMSA activity here!](/activities/act-2.qmd)
