---
subtitle: "Week 13: AWS Networking, EC2, ECS and ECR"
format: revealjs
---

# Goals for today

- Understand AWS Networking `https://scribe.rip/@AlexanderObregon/aws-networking-fundamentals-for-beginners-86dfb35ccc03`
- Understand what is AWS EC2.
- Understand what is AWS ECR.
- Understand what is AWS ECS.

# Recap

- TODO: Remember VM's vs containers
- TODO: What we did until now (everything local...)
- TODO: Remember that the aws cloud ui is s\*\*t, that's why there are frontends like Vercel, etc. That facture 1-2 billion dollars (and are just a visual frontend for AWS..)
	
# Virtualization
  
# Quizz {.smaller}
  
  - Lorem
  - ipsum
  - Ipsum
  
# References

## Really Recommended References: {.smaller}

- [LWN.net article's set about namespaces](https://lwn.net/Articles/531114/)

- [Docker Arch Wiki](https://wiki.archlinux.org/title/Docker)

- [Microsoft: What is a contaner](https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-a-container/#overview)

- [Docker Containers vs Docker Images](https://www.educba.com/docker-containers-vs-images/)

- [Docker, Kubernetes and MicroServices](/extras/kubernetes-docker-pablo-fraile.pdf)

## Additional Exercices {#extra .smaller}

If you really want to understand a little bit more what happens under the hood, you can do the following exercices. Be aware that you should read the "Really Recommended References" first, and then try to do this exercices.

- Create a container that runs a wordpress instance and access it via http://localhost:8080

